feat : Abstraction in java
dev-madhurendra/OOPs pull request #26
Opened 2023-09-24 15:37 UTC by Suryac72

### Describe your change

- [ ] Add a concept ?
- [ ] Fix a bug or typo in an existing concept ?
- [ ] Documentation change?

### Checklist

- [ ] I have read [CONTRIBUTING.md](https://github.com/dev-madhurendra/OOPs/blob/main/CONTRIBUTING.md).
- [ ] This pull request is all my own work -- I have not plagiarized.
- [ ] I know that pull requests will not be merged if they fail the automated tests.
- [ ] This PR only changes one file. To ease review, please open separate PRs for separate concepts.
- [ ] All new folders are placed in an existing directory.
- [ ] All new files are placed inside an existing directory.
- [ ] All folder names should use the UpperCamelCase (PascalCase) style. There should be no spaces in filenames.
      **Example:**`Golang` is allowed but `golang` is not
- [ ] All filenames should use the UpperCamelCase (PascalCase) style. There should be no spaces in filenames.
      **Example:**`Class.cpp` is allowed but `classe.cpp` is not
- [ ] All new concepts have a URL in their comments that points to Wikipedia or another similar explanation.
- [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`

2023-09-24 16:11 UTC, dev-madhurendra requested changes

2023-09-24 16:11 UTC, dev-madhurendra commented on Java/Abstraction/Abstraction.java
> +    obj.run();
What will be the output of it ?
comment that thing here.

2023-09-24 16:11 UTC, dev-madhurendra commented on Java/Abstraction/Abstraction.java
> +}
Abstract classes can also have regular methods with implementations isn't it ? Think about every aspects and add those things as well.

2023-09-29 07:11 UTC, Suryac72 commented
hi @dev-madhurendra  PR update, I implement abstraction using abstract class as well as interface. for output comment, it will be self explanatory for everyone so, I not add any comment for that

2023-09-29 08:15 UTC, dev-madhurendra approved these changes

2023-09-29 08:15 UTC, merged