added basic of classes and objects in python
dev-madhurendra/OOPs pull request #27
Opened 2023-09-24 16:51 UTC by Khanna14Aman

### Describe your change

- [ ] Add a concept ?
- [ ] Fix a bug or typo in an existing concept ?
- [ ] Documentation change?

### Checklist

- [ ] I have read [CONTRIBUTING.md](https://github.com/dev-madhurendra/OOPs/blob/main/CONTRIBUTING.md).
- [ ] This pull request is all my own work -- I have not plagiarized.
- [ ] I know that pull requests will not be merged if they fail the automated tests.
- [ ] This PR only changes one file. To ease review, please open separate PRs for separate concepts.
- [ ] All new folders are placed in an existing directory.
- [ ] All new files are placed inside an existing directory.
- [ ] All folder names should use the UpperCamelCase (PascalCase) style. There should be no spaces in filenames.
      **Example:**`Golang` is allowed but `golang` is not
- [ ] All filenames should use the UpperCamelCase (PascalCase) style. There should be no spaces in filenames.
      **Example:**`Class.cpp` is allowed but `classe.cpp` is not
- [ ] All new concepts have a URL in their comments that points to Wikipedia or another similar explanation.
- [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`

2023-09-24 16:59 UTC, dev-madhurendra approved these changes

2023-09-24 17:02 UTC, dev-madhurendra requested changes

2023-09-24 17:02 UTC, dev-madhurendra commented on Python/Class/Class.py
> +# Here we define a new class named "First"
But here class name is Bike you written First

2023-09-25 07:20 UTC, dev-madhurendra commented
Hi @Khanna14Aman , I am approving this PR but follow the naming convention of branch,file,folder name e.g. branch name for this should be : Python_Class

2023-09-25 07:21 UTC, dev-madhurendra approved these changes
Also write proper comment for the concepts so that anyone can understand easily by just reading.

2023-09-25 14:51 UTC, Suryac72 approved these changes
Good from my end, handover to @dev-madhurendra

2023-09-25 14:52 UTC, merged